name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  owoify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: ./owoify.sh
  bottomify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run
      run: ./bottomify.sh
